/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotFoundIndexRouteImport } from './routes/not-found.index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as ContactUsIndexRouteImport } from './routes/contact-us.index'
import { Route as ServicesOfferedSlugRouteImport } from './routes/services-offered.$slug'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiRemyChatRouteImport } from './routes/api.remy-chat'
import { Route as ApiContactUsFormIndexRouteImport } from './routes/api/contact-us-form/index'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/_api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/_api.names'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundIndexRoute = NotFoundIndexRouteImport.update({
  id: '/not-found/',
  path: '/not-found/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsIndexRoute = ContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOfferedSlugRoute = ServicesOfferedSlugRouteImport.update({
  id: '/services-offered/$slug',
  path: '/services-offered/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/gallery/$slug',
  path: '/gallery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemyChatRoute = ApiRemyChatRouteImport.update({
  id: '/api/remy-chat',
  path: '/api/remy-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactUsFormIndexRoute = ApiContactUsFormIndexRouteImport.update({
  id: '/api/contact-us-form/',
  path: '/api/contact-us-form/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/_api/tq-todos',
  path: '/demo/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/_api/names',
  path: '/demo/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/services-offered/$slug': typeof ServicesOfferedSlugRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/not-found/': typeof NotFoundIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/names': typeof DemoApiNamesRoute
  '/demo/tq-todos': typeof DemoApiTqTodosRoute
  '/api/contact-us-form/': typeof ApiContactUsFormIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/services-offered/$slug': typeof ServicesOfferedSlugRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/not-found': typeof NotFoundIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/names': typeof DemoApiNamesRoute
  '/demo/tq-todos': typeof DemoApiTqTodosRoute
  '/api/contact-us-form': typeof ApiContactUsFormIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/services-offered/$slug': typeof ServicesOfferedSlugRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/not-found/': typeof NotFoundIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/_api/names': typeof DemoApiNamesRoute
  '/demo/_api/tq-todos': typeof DemoApiTqTodosRoute
  '/api/contact-us-form/': typeof ApiContactUsFormIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/remy-chat'
    | '/demo/better-auth'
    | '/gallery/$slug'
    | '/services-offered/$slug'
    | '/contact-us/'
    | '/gallery/'
    | '/not-found/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/demo/names'
    | '/demo/tq-todos'
    | '/api/contact-us-form/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/remy-chat'
    | '/demo/better-auth'
    | '/gallery/$slug'
    | '/services-offered/$slug'
    | '/contact-us'
    | '/gallery'
    | '/not-found'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/demo/names'
    | '/demo/tq-todos'
    | '/api/contact-us-form'
  id:
    | '__root__'
    | '/'
    | '/api/remy-chat'
    | '/demo/better-auth'
    | '/gallery/$slug'
    | '/services-offered/$slug'
    | '/contact-us/'
    | '/gallery/'
    | '/not-found/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/demo/_api/names'
    | '/demo/_api/tq-todos'
    | '/api/contact-us-form/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRemyChatRoute: typeof ApiRemyChatRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  GallerySlugRoute: typeof GallerySlugRoute
  ServicesOfferedSlugRoute: typeof ServicesOfferedSlugRoute
  ContactUsIndexRoute: typeof ContactUsIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  NotFoundIndexRoute: typeof NotFoundIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  ApiContactUsFormIndexRoute: typeof ApiContactUsFormIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found/': {
      id: '/not-found/'
      path: '/not-found'
      fullPath: '/not-found/'
      preLoaderRoute: typeof NotFoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us/': {
      id: '/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us/'
      preLoaderRoute: typeof ContactUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services-offered/$slug': {
      id: '/services-offered/$slug'
      path: '/services-offered/$slug'
      fullPath: '/services-offered/$slug'
      preLoaderRoute: typeof ServicesOfferedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/gallery/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remy-chat': {
      id: '/api/remy-chat'
      path: '/api/remy-chat'
      fullPath: '/api/remy-chat'
      preLoaderRoute: typeof ApiRemyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact-us-form/': {
      id: '/api/contact-us-form/'
      path: '/api/contact-us-form'
      fullPath: '/api/contact-us-form/'
      preLoaderRoute: typeof ApiContactUsFormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/_api/tq-todos': {
      id: '/demo/_api/tq-todos'
      path: '/demo/tq-todos'
      fullPath: '/demo/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/_api/names': {
      id: '/demo/_api/names'
      path: '/demo/names'
      fullPath: '/demo/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRemyChatRoute: ApiRemyChatRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  GallerySlugRoute: GallerySlugRoute,
  ServicesOfferedSlugRoute: ServicesOfferedSlugRoute,
  ContactUsIndexRoute: ContactUsIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  NotFoundIndexRoute: NotFoundIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  ApiContactUsFormIndexRoute: ApiContactUsFormIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
