/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiContactUsIndexRouteImport } from './routes/api/contact-us/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactUsIndexRoute = ApiContactUsIndexRouteImport.update({
  id: '/api/contact-us/',
  path: '/api/contact-us/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/services': typeof ServicesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/contact-us/': typeof ApiContactUsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/services': typeof ServicesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/contact-us': typeof ApiContactUsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/services': typeof ServicesRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/contact-us/': typeof ApiContactUsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/gallery'
    | '/mcp'
    | '/services'
    | '/projects/$slug'
    | '/api/auth/$'
    | '/api/contact-us/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/gallery'
    | '/mcp'
    | '/services'
    | '/projects/$slug'
    | '/api/auth/$'
    | '/api/contact-us'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/gallery'
    | '/mcp'
    | '/services'
    | '/projects/$slug'
    | '/api/auth/$'
    | '/api/contact-us/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  McpRoute: typeof McpRoute
  ServicesRoute: typeof ServicesRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiContactUsIndexRoute: typeof ApiContactUsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact-us/': {
      id: '/api/contact-us/'
      path: '/api/contact-us'
      fullPath: '/api/contact-us/'
      preLoaderRoute: typeof ApiContactUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  McpRoute: McpRoute,
  ServicesRoute: ServicesRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiContactUsIndexRoute: ApiContactUsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
