/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalksIndexRouteImport } from './routes/talks.index'
import { Route as ServicesOfferedIndexRouteImport } from './routes/services-offered.index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as TalksSlugRouteImport } from './routes/talks.$slug'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as ApiRemyChatRouteImport } from './routes/api.remy-chat'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/_api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/_api.names'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksIndexRoute = TalksIndexRouteImport.update({
  id: '/talks/',
  path: '/talks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOfferedIndexRoute = ServicesOfferedIndexRouteImport.update({
  id: '/services-offered/',
  path: '/services-offered/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalksSlugRoute = TalksSlugRouteImport.update({
  id: '/talks/$slug',
  path: '/talks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/gallery/$slug',
  path: '/gallery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemyChatRoute = ApiRemyChatRouteImport.update({
  id: '/api/remy-chat',
  path: '/api/remy-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/_api/tq-todos',
  path: '/demo/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/_api/names',
  path: '/demo/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/gallery/': typeof GalleryIndexRoute
  '/services-offered/': typeof ServicesOfferedIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/names': typeof DemoApiNamesRoute
  '/demo/tq-todos': typeof DemoApiTqTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/gallery': typeof GalleryIndexRoute
  '/services-offered': typeof ServicesOfferedIndexRoute
  '/talks': typeof TalksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/names': typeof DemoApiNamesRoute
  '/demo/tq-todos': typeof DemoApiTqTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/remy-chat': typeof ApiRemyChatRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/talks/$slug': typeof TalksSlugRoute
  '/gallery/': typeof GalleryIndexRoute
  '/services-offered/': typeof ServicesOfferedIndexRoute
  '/talks/': typeof TalksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/demo/_api/names': typeof DemoApiNamesRoute
  '/demo/_api/tq-todos': typeof DemoApiTqTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/remy-chat'
    | '/demo/better-auth'
    | '/gallery/$slug'
    | '/talks/$slug'
    | '/gallery/'
    | '/services-offered/'
    | '/talks/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/demo/names'
    | '/demo/tq-todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/remy-chat'
    | '/demo/better-auth'
    | '/gallery/$slug'
    | '/talks/$slug'
    | '/gallery'
    | '/services-offered'
    | '/talks'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/demo/names'
    | '/demo/tq-todos'
  id:
    | '__root__'
    | '/'
    | '/api/remy-chat'
    | '/demo/better-auth'
    | '/gallery/$slug'
    | '/talks/$slug'
    | '/gallery/'
    | '/services-offered/'
    | '/talks/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/demo/_api/names'
    | '/demo/_api/tq-todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRemyChatRoute: typeof ApiRemyChatRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  GallerySlugRoute: typeof GallerySlugRoute
  TalksSlugRoute: typeof TalksSlugRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  ServicesOfferedIndexRoute: typeof ServicesOfferedIndexRoute
  TalksIndexRoute: typeof TalksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/': {
      id: '/talks/'
      path: '/talks'
      fullPath: '/talks/'
      preLoaderRoute: typeof TalksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services-offered/': {
      id: '/services-offered/'
      path: '/services-offered'
      fullPath: '/services-offered/'
      preLoaderRoute: typeof ServicesOfferedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talks/$slug': {
      id: '/talks/$slug'
      path: '/talks/$slug'
      fullPath: '/talks/$slug'
      preLoaderRoute: typeof TalksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/gallery/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remy-chat': {
      id: '/api/remy-chat'
      path: '/api/remy-chat'
      fullPath: '/api/remy-chat'
      preLoaderRoute: typeof ApiRemyChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/_api/tq-todos': {
      id: '/demo/_api/tq-todos'
      path: '/demo/tq-todos'
      fullPath: '/demo/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/_api/names': {
      id: '/demo/_api/names'
      path: '/demo/names'
      fullPath: '/demo/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRemyChatRoute: ApiRemyChatRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  GallerySlugRoute: GallerySlugRoute,
  TalksSlugRoute: TalksSlugRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  ServicesOfferedIndexRoute: ServicesOfferedIndexRoute,
  TalksIndexRoute: TalksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
