name: Code quality check
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          node-version: 20

      - name: run frozen install
        run: pnpm install --frozen-lockfile
          
      - name: run sanity
        run: pnpm run sanity
